name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-149.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.8
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.8

  # UI
  flextras: ^1.0.0 
  boxy: ^2.1.3
  flutter_portal: ^1.1.4
  flutter_animate: ^4.3.0

  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
