version: '3.9'
networks:
  net:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7777:7777
    env_file:
      - env/production.env
    depends_on:
      - db
    networks:
      - net
  db:
    image: ghcr.io/chroma-core/chroma:0.4.18
    volumes:
      - index_data:/index_data
    ports:
      - 8000:8000
    networks:
      - net
volumes:
  index_data:
    driver: local
  backups:
    driver: local