version: '3.9'
networks:
  net:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7777:7777
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local