name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0

  # LLM-Server
  langchain: ^0.1.1+1
  langchain_google: ^0.1.0+4
  langchain_openai: ^0.1.2+2

  # Server
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4

  # Http client
  http: ^1.1.1

  # Json
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
