name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  langchain: ^0.1.1+1
  langchain_google: ^0.1.0+4
  langchain_openai: ^0.1.2+2
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
