name: shared
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  html: ^0.15.4 

  # Json
  json_annotation: ^4.8.1

  copy_with_extension: ^5.0.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
